### ISSUE TITLE
Add tooltips to icon buttons

### ISSUE THREAD

**Issue by ProbablyFaiz** [DrDocx/DrDocx-Electron#5]
We should have tooltips when a user hovers over an icon button so they can figure out what it is. For example, the new field options should have tooltips:
<img width="324" alt="Screen Shot 2020-02-28 at 4 32 31 PM" src="https://user-images.githubusercontent.com/34611522/75596999-ec307d00-5a47-11ea-9f0d-b5ff054388f4.png">

**Comment by hari387** [comment]
Added tooltips to all icons in most recent commit.
